"""
Renders scoreboard-site/index.html -- the Scoreboard: every game outcome
in one stadium-style board.

  - Latest round: big scoreboard tiles (final score, W/D/L, goal scorers
    with minute and goal type).
  - League table built from every resolved result (3/1/0, tiebreak GD
    then GF -- same rule as simulate.Standings), with last-5 form.
  - Every round's results, newest first, with round tabs.

Before any round is resolved it shows Round 1's fixtures as "upcoming"
and an all-zero table, so the page is useful from day one.

Reads data/matches.json, data/schedule.json, data/season_calendar.json,
data/league_config.json. Regenerated by auto_resolve.regenerate_all_pages()
after every resolve, so it updates itself.
"""
import datetime
import html
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from site_nav import GH_BASE, NAV_CSS, render_nav

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_json(name):
    with open(os.path.join(BASE, "data", name)) as f:
        return json.load(f)


def esc(s):
    return html.escape(str(s))


def render(config, schedule, calendar, matches):
    teams = config["teams"]
    name_by_id = {t["team_id"]: t["name"] for t in teams}
    owner_by_id = {t["team_id"]: t.get("owner", "") for t in teams}
    name = lambda tid: esc(name_by_id.get(tid, f"Team {tid}"))
    owner = lambda tid: esc(owner_by_id.get(tid, ""))

    date_by_round = {}
    for entry in calendar.get("match_day_schedule", []):
        for r in entry["rounds"]:
            date_by_round[r] = entry["date"]

    def fmt_date(d):
        try:
            return datetime.date.fromisoformat(d).strftime("%a %b %-d")
        except (TypeError, ValueError):
            return "TBD"

    # ---- league table (regular season only, same rule as simulate.Standings) ----
    table = {t["team_id"]: {"P": 0, "W": 0, "D": 0, "L": 0, "GF": 0, "GA": 0, "PTS": 0, "form": []} for t in teams}
    regular = [m for m in matches if m.get("stage", "regular") == "regular"]
    for m in sorted(regular, key=lambda m: m["round"]):
        h, a, hg, ag = m["home_id"], m["away_id"], m["home_goals"], m["away_goals"]
        if h not in table or a not in table:
            continue
        H, A = table[h], table[a]
        H["P"] += 1; A["P"] += 1
        H["GF"] += hg; H["GA"] += ag; A["GF"] += ag; A["GA"] += hg
        if hg > ag:
            H["W"] += 1; H["PTS"] += 3; A["L"] += 1; H["form"].append("W"); A["form"].append("L")
        elif hg < ag:
            A["W"] += 1; A["PTS"] += 3; H["L"] += 1; H["form"].append("L"); A["form"].append("W")
        else:
            H["D"] += 1; A["D"] += 1; H["PTS"] += 1; A["PTS"] += 1; H["form"].append("D"); A["form"].append("D")
    ranked = sorted(table.items(), key=lambda kv: (-kv[1]["PTS"], -(kv[1]["GF"] - kv[1]["GA"]), -kv[1]["GF"], name_by_id.get(kv[0], "")))
    playoff_n = config.get("playoff_teams", 0) or 0

    table_rows = []
    for pos, (tid, r) in enumerate(ranked, 1):
        gd = r["GF"] - r["GA"]
        form = "".join(f'<span class="f f-{x}">{x}</span>' for x in r["form"][-5:]) or '<span class="muted">&mdash;</span>'
        cls = ' class="po"' if playoff_n and pos <= playoff_n and r["P"] else ""
        table_rows.append(
            f'<tr{cls}><td class="pos">{pos}</td><td class="tm"><b>{name(tid)}</b><small>{owner(tid)}</small></td>'
            f'<td>{r["P"]}</td><td>{r["W"]}</td><td>{r["D"]}</td><td>{r["L"]}</td><td>{r["GF"]}</td><td>{r["GA"]}</td>'
            f'<td>{"+" if gd > 0 else ""}{gd}</td><td class="pts">{r["PTS"]}</td><td class="form">{form}</td></tr>')

    # ---- results by round ----
    by_round = {}
    for m in matches:
        by_round.setdefault((m["round"], m.get("stage", "regular")), []).append(m)
    played_keys = sorted(by_round, key=lambda k: (k[1] != "regular", k[0]))  # regular rounds first, then playoffs

    def scorers(m, side):
        evs = [e for e in m.get("goal_events", []) if e.get("side") == side]
        return "".join(f'<li><span class="min">{e["minute"]}&prime;</span>{esc(e.get("scorer", ""))}'
                       f'<em>{esc(e.get("type", ""))}</em></li>' for e in sorted(evs, key=lambda e: e["minute"]))

    def tile(m):
        h, a, hg, ag = m["home_id"], m["away_id"], m["home_goals"], m["away_goals"]
        hres = "w" if hg > ag else ("l" if hg < ag else "d")
        ares = {"w": "l", "l": "w", "d": "d"}[hres]
        return f'''<article class="tile">
  <div class="side {hres}"><span class="ha">Home</span><b>{name(h)}</b><small>{owner(h)}</small><ul class="sc">{scorers(m, "home")}</ul></div>
  <div class="score"><span class="dig">{hg}</span><span class="dash">&ndash;</span><span class="dig">{ag}</span><span class="ft">FT</span></div>
  <div class="side {ares} right"><span class="ha">Away</span><b>{name(a)}</b><small>{owner(a)}</small><ul class="sc">{scorers(m, "away")}</ul></div>
</article>'''

    def upcoming_tile(h, a):
        return f'''<article class="tile up">
  <div class="side"><span class="ha">Home</span><b>{name(h)}</b><small>{owner(h)}</small></div>
  <div class="score"><span class="dig off">&ndash;</span><span class="dash">:</span><span class="dig off">&ndash;</span><span class="ft">VS</span></div>
  <div class="side right"><span class="ha">Away</span><b>{name(a)}</b><small>{owner(a)}</small></div>
</article>'''

    def round_label(key):
        rnum, stage = key
        return f"Round {rnum}" if stage == "regular" else f"{stage.title()} &middot; Round {rnum}"

    # latest board
    if played_keys:
        latest = played_keys[-1]
        hero_title = f'{round_label(latest)} &middot; Final'
        hero_meta = fmt_date(date_by_round.get(latest[0])) if latest[1] == "regular" else ""
        hero_tiles = "".join(tile(m) for m in by_round[latest])
    else:
        first = schedule[0] if schedule else {"round": 1, "fixtures": []}
        hero_title = f'Round {first["round"]} &middot; Upcoming'
        hero_meta = fmt_date(date_by_round.get(first["round"]))
        hero_tiles = "".join(upcoming_tile(fx["home_id"], fx["away_id"]) for fx in first["fixtures"])

    total_goals = sum(m["home_goals"] + m["away_goals"] for m in matches)
    n_played = len(matches)
    n_sched = sum(len(r["fixtures"]) for r in schedule)
    biggest = max(matches, key=lambda m: (abs(m["home_goals"] - m["away_goals"]), m["home_goals"] + m["away_goals"]), default=None)
    big_txt = (f'{name(biggest["home_id"])} {biggest["home_goals"]}&ndash;{biggest["away_goals"]} {name(biggest["away_id"])}'
               if biggest and biggest["home_goals"] != biggest["away_goals"] else "&mdash;")

    # all rounds (newest first)
    tabs, panels = [], []
    for i, key in enumerate(reversed(played_keys)):
        rid = f'r{key[0]}{"" if key[1] == "regular" else "-" + key[1]}'
        tabs.append(f'<button type="button" class="tab{" on" if i == 0 else ""}" data-t="{rid}">{round_label(key)}</button>')
        rows = []
        for m in by_round[key]:
            h, a, hg, ag = m["home_id"], m["away_id"], m["home_goals"], m["away_goals"]
            rows.append(f'<tr><td class="r {"win" if hg > ag else ""}">{name(h)}</td><td class="c"><span class="mini">{hg}&ndash;{ag}</span></td>'
                        f'<td class="l {"win" if ag > hg else ""}">{name(a)}</td></tr>')
        date = fmt_date(date_by_round.get(key[0])) if key[1] == "regular" else ""
        panels.append(f'<div class="panel{" on" if i == 0 else ""}" id="{rid}"><p class="pdate">{date}</p>'
                      f'<table class="res"><tbody>{"".join(rows)}</tbody></table></div>')
    rounds_html = (f'<div class="tabs">{"".join(tabs)}</div>{"".join(panels)}' if played_keys
                   else '<p class="empty">No results yet &mdash; scores appear here automatically as soon as each round is played.</p>')

    league = esc(config["league_name"])
    updated = datetime.datetime.now().strftime("%b %-d, %Y %-I:%M %p")

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Scoreboard</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@600;700;800;900&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=IBM+Plex+Mono:wght@400;500;600&display=swap">
<style>
:root{{
  --paper:#eef2ea; --ink:#0c120e; --accent:#f2b632;
  --board:#0b100d; --board2:#141b16; --line:#26302a; --txt:#eef2ea; --muted:#8c9a8e;
  --led:#ffb627; --win:#4fd18b; --loss:#ff7a5c; --draw:#e6c45a; --pitch:#1f4a2c;
}}
@media (prefers-color-scheme: dark){{ :root:not([data-theme="light"]){{ --paper:#e7ece1; --ink:#070b08; }} }}
:root[data-theme="dark"]{{ --paper:#e7ece1; --ink:#070b08; }}
*{{box-sizing:border-box;}}
body{{margin:0;background:radial-gradient(1200px 500px at 50% -150px,#1d3b27 0%,transparent 70%),var(--board);color:var(--txt);font-family:"Source Serif 4",Georgia,serif;line-height:1.45;}}
h1,h2,h3{{font-family:"Big Shoulders Display",sans-serif;text-transform:uppercase;letter-spacing:.03em;margin:0;}}
.wrap{{max-width:1240px;margin:0 auto;padding:26px clamp(14px,4vw,44px) 70px;}}
.mast{{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:20px;}}
.mast h1{{font-size:clamp(34px,6vw,64px);font-weight:900;line-height:.9;color:var(--led);text-shadow:0 0 18px rgba(255,182,39,.45);}}
.mast p{{margin:6px 0 0;font-family:"IBM Plex Mono",monospace;font-size:12.5px;color:var(--muted);letter-spacing:.04em;}}
.kpis{{display:flex;gap:10px;flex-wrap:wrap;}}
.kpi{{background:var(--board2);border:1px solid var(--line);border-radius:10px;padding:8px 14px;min-width:110px;}}
.kpi span{{display:block;font-family:"IBM Plex Mono",monospace;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);}}
.kpi b{{font-family:"Big Shoulders Display",sans-serif;font-size:26px;color:var(--txt);}}
.kpi.wide b{{font-size:16px;}}

.sec-h{{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin:30px 0 12px;border-bottom:2px solid var(--led);padding-bottom:6px;}}
.sec-h h2{{font-size:26px;}} .sec-h span{{font-family:"IBM Plex Mono",monospace;font-size:12px;color:var(--muted);}}

.board{{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:12px;}}
.tile{{display:grid;grid-template-columns:1fr auto 1fr;align-items:start;gap:10px;background:linear-gradient(180deg,#121a15,#0d130f);
  border:1px solid var(--line);border-radius:12px;padding:14px;box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 8px 24px rgba(0,0,0,.35);}}
.side{{min-width:0;}} .side.right{{text-align:right;}}
.side b{{display:block;font-family:"Big Shoulders Display",sans-serif;font-weight:800;font-size:21px;line-height:1.05;text-transform:uppercase;overflow-wrap:anywhere;}}
.side small{{display:block;font-family:"IBM Plex Mono",monospace;font-size:10.5px;color:var(--muted);margin-top:2px;}}
.ha{{font-family:"IBM Plex Mono",monospace;font-size:9.5px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);}}
.side.w b{{color:var(--win);}} .side.l b{{color:#c9d2ca;opacity:.75;}} .side.d b{{color:var(--draw);}}
.score{{display:flex;align-items:center;gap:4px;padding-top:12px;position:relative;}}
.dig{{display:inline-flex;align-items:center;justify-content:center;min-width:46px;height:58px;border-radius:7px;background:#050806;border:1px solid #1d261f;
  font-family:"Big Shoulders Display",sans-serif;font-weight:900;font-size:44px;color:var(--led);text-shadow:0 0 12px rgba(255,182,39,.6);}}
.dig.off{{color:#3b463e;text-shadow:none;}}
.dash{{font-family:"Big Shoulders Display",sans-serif;font-size:30px;color:var(--muted);}}
.ft{{position:absolute;left:50%;top:-6px;transform:translateX(-50%);font-family:"IBM Plex Mono",monospace;font-size:9.5px;letter-spacing:.14em;color:var(--muted);}}
.sc{{list-style:none;margin:8px 0 0;padding:0;font-size:12.5px;}}
.sc li{{margin:2px 0;}} .side.right .sc li{{direction:ltr;}}
.sc .min{{font-family:"IBM Plex Mono",monospace;color:var(--led);margin-right:5px;font-size:11.5px;}}
.sc em{{display:block;font-style:normal;font-family:"IBM Plex Mono",monospace;font-size:10px;color:var(--muted);}}

.grid2{{display:grid;grid-template-columns:1.25fr 1fr;gap:26px;align-items:start;}}
.tbl{{width:100%;border-collapse:collapse;font-size:13.5px;background:var(--board2);border:1px solid var(--line);border-radius:10px;overflow:hidden;font-variant-numeric:tabular-nums;}}
.tbl th{{background:#050806;color:var(--led);font-family:"IBM Plex Mono",monospace;font-size:10.5px;letter-spacing:.08em;text-transform:uppercase;padding:9px 8px;text-align:center;}}
.tbl th:nth-child(2){{text-align:left;}}
.tbl td{{padding:7px 8px;border-top:1px solid var(--line);text-align:center;}}
.tbl td.tm{{text-align:left;}} .tbl td.tm b{{display:block;font-weight:600;}} .tbl td.tm small{{color:var(--muted);font-family:"IBM Plex Mono",monospace;font-size:10.5px;}}
.tbl td.pos{{font-family:"Big Shoulders Display",sans-serif;font-size:18px;color:var(--muted);width:34px;}}
.tbl td.pts{{font-family:"Big Shoulders Display",sans-serif;font-size:20px;font-weight:800;color:var(--led);}}
.tbl tr.po td.pos{{color:var(--win);box-shadow:inset 3px 0 0 var(--win);}}
.form{{white-space:nowrap;}}
.f{{display:inline-flex;align-items:center;justify-content:center;width:19px;height:19px;border-radius:4px;margin:0 1px;font:600 10.5px "IBM Plex Mono",monospace;color:#07100a;}}
.f-W{{background:var(--win);}} .f-L{{background:var(--loss);}} .f-D{{background:var(--draw);}}
.muted{{color:var(--muted);}}
.legend{{font-family:"IBM Plex Mono",monospace;font-size:11px;color:var(--muted);margin:8px 2px 0;}}
.legend i{{display:inline-block;width:10px;height:10px;background:var(--win);border-radius:2px;margin-right:5px;vertical-align:-1px;}}

.tabs{{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px;}}
.tab{{background:var(--board2);border:1px solid var(--line);color:var(--txt);border-radius:999px;padding:5px 12px;cursor:pointer;font:500 12px "IBM Plex Mono",monospace;}}
.tab.on{{background:var(--led);color:#1a1205;border-color:var(--led);font-weight:600;}}
.panel{{display:none;}} .panel.on{{display:block;}}
.pdate{{margin:0 0 6px;font-family:"IBM Plex Mono",monospace;font-size:12px;color:var(--muted);}}
.res{{width:100%;border-collapse:collapse;background:var(--board2);border:1px solid var(--line);border-radius:10px;overflow:hidden;font-size:14px;}}
.res td{{padding:8px 10px;border-top:1px solid var(--line);}} .res tr:first-child td{{border-top:0;}}
.res td.r{{text-align:right;width:44%;}} .res td.l{{width:44%;}} .res td.c{{text-align:center;}}
.res td.win{{color:var(--win);font-weight:600;}}
.mini{{display:inline-block;min-width:54px;padding:2px 8px;border-radius:5px;background:#050806;color:var(--led);font:700 16px "Big Shoulders Display",sans-serif;letter-spacing:.06em;}}
.empty{{background:var(--board2);border:1px dashed var(--line);border-radius:10px;padding:18px;color:var(--muted);font-family:"IBM Plex Mono",monospace;font-size:13px;}}
footer{{max-width:1240px;margin:0 auto;padding:0 clamp(14px,4vw,44px) 40px;color:var(--muted);font-size:12px;font-family:"IBM Plex Mono",monospace;}}
footer a{{color:var(--led);}}
@media (max-width:900px){{ .grid2{{grid-template-columns:1fr;}} .board{{grid-template-columns:1fr;}} }}
@media (max-width:520px){{ .tbl th:nth-child(n+5):nth-child(-n+8),.tbl td:nth-child(n+5):nth-child(-n+8){{display:none;}} .dig{{min-width:38px;height:48px;font-size:34px;}} }}
{NAV_CSS}
</style>
</head>
<body>
{render_nav("scoreboard")}
<div class="wrap">
  <div class="mast">
    <div><h1>Scoreboard</h1><p>{league} &middot; every game outcome, updated automatically after each round &middot; last updated {updated}</p></div>
    <div class="kpis">
      <div class="kpi"><span>Games played</span><b>{n_played} / {n_sched}</b></div>
      <div class="kpi"><span>Total goals</span><b>{total_goals}</b></div>
      <div class="kpi"><span>Goals / game</span><b>{(total_goals / n_played) if n_played else 0:.2f}</b></div>
      <div class="kpi wide"><span>Biggest win</span><b>{big_txt}</b></div>
    </div>
  </div>

  <div class="sec-h"><h2>{hero_title}</h2><span>{hero_meta}</span></div>
  <div class="board">{hero_tiles}</div>

  <div class="grid2">
    <section>
      <div class="sec-h"><h2>League Table</h2><span>3 pts win &middot; 1 draw &middot; tiebreak GD, then GF</span></div>
      <div style="overflow-x:auto"><table class="tbl"><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th><th>Form</th></tr></thead>
      <tbody>{"".join(table_rows)}</tbody></table></div>
      {f'<p class="legend"><i></i>Top {playoff_n} = playoff spots</p>' if playoff_n else ''}
    </section>
    <section>
      <div class="sec-h"><h2>All Results</h2><span><a href="{GH_BASE}/matchday-replay/" style="color:var(--led)">Watch replays &rarr;</a></span></div>
      {rounds_html}
    </section>
  </div>
</div>
<footer>{league} &middot; results are permanent once resolved &middot; full fixture list on the <a href="{GH_BASE}/schedule/">Schedule</a></footer>
<script>
document.querySelectorAll('.tab').forEach(function(b){{b.addEventListener('click',function(){{
  document.querySelectorAll('.tab').forEach(function(x){{x.classList.toggle('on',x===b);}});
  document.querySelectorAll('.panel').forEach(function(p){{p.classList.toggle('on',p.id===b.dataset.t);}});
}});}});
</script>
</body>
</html>'''


if __name__ == "__main__":
    html_out = render(load_json("league_config.json"), load_json("schedule.json"),
                      load_json("season_calendar.json"), load_json("matches.json"))
    out_dir = os.path.join(BASE, "scoreboard-site")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w") as f:
        f.write(html_out)
    print(f"Rendered -> {out_dir}/index.html")
