"""
Renders health-site/index.html -- the Player Health Hub page: treatment
catalog and rules, next round's condition/injury status for every rostered
player, each team's cash and treatments used, the PIN-checked request form
(assets/health.js), and the public treatment log. Rules and effects live in
engine/health.py; this page only displays them. Regenerated by
auto_resolve.regenerate_all_pages() after every resolve or applied request.
"""
import json
import os
import sys
from html import escape

sys.path.insert(0, os.path.dirname(__file__))
from site_nav import NAV_CSS, render_nav
import render_dashboard
import resolve_trade
import health
from player_condition import conditions_for_round

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_json(name, default=None):
    path = os.path.join(BASE, "data", name)
    if not os.path.exists(path):
        return default
    with open(path) as f:
        return json.load(f)


def money(n):
    return f"${n:,}"


def render(config, players, finances, injuries, state):
    next_round = config.get("current_round", 0) + 1
    n_rounds = len(load_json("schedule.json", []))
    trades_state = resolve_trade.load_trades_state()
    _m, detail = conditions_for_round(config.get("season_seed", 2026), next_round, players, injuries)
    team_name = {str(t["team_id"]): t["name"] for t in config["teams"]}

    roster = []
    for p in players:
        if p["team_id"] in ("", None):
            continue
        tier, _mult, inj_until = detail.get(p["player_id"], ("Average", 1.0, None))
        roster.append({"id": p["player_id"], "name": p["name"], "pos": p["position"], "ovr": p["ovr"],
                       "team_id": str(p["team_id"]), "cond": tier, "injured_until": inj_until})
    roster.sort(key=lambda r: ({"GK": 0, "DF": 1, "MF": 2, "FW": 3}.get(r["pos"], 4), -r["ovr"]))

    used = {}
    for a in state["applied"]:
        if a["round"] == next_round:
            used[a["team_id"]] = used.get(a["team_id"], 0) + 1
    teams = {str(t["team_id"]): {"name": t["name"],
                                 "cash": resolve_trade.team_available_cash(finances, config, trades_state, t["team_id"]),
                                 "spent": health.team_spend(t["team_id"], state),
                                 "used": used.get(str(t["team_id"]), 0)} for t in config["teams"]}
    open_now = next_round >= health.START_ROUND and next_round <= n_rounds
    data = {"next_round": next_round, "start_round": health.START_ROUND, "max_per_round": health.MAX_PER_ROUND,
            "open": open_now, "catalog": health.CATALOG, "players": roster, "teams": teams}

    cat_rows = "".join(
        f'<tr><td>{escape(t["label"])}</td><td>{"Injured players" if t["kind"] == "injury" else "Healthy players"}</td>'
        f'<td>{escape(t["effect"])}</td><td class="num mono">{money(t["cost"])}</td></tr>'
        for t in health.CATALOG.values())

    team_rows = "".join(
        f'<tr><td>{escape(v["name"])}</td><td class="num mono">{money(v["cash"])}</td>'
        f'<td class="num mono">{money(v["spent"])}</td><td class="num mono">{v["used"]} / {health.MAX_PER_ROUND}</td></tr>'
        for _k, v in sorted(teams.items(), key=lambda kv: int(kv[0])))

    injured_rows = "".join(
        f'<tr><td>{escape(team_name.get(r["team_id"], ""))}</td><td>{escape(r["name"])}</td><td>{r["pos"]}</td>'
        f'<td class="num mono">{r["ovr"]}</td><td class="num mono">Round {r["injured_until"]}</td></tr>'
        for r in sorted(roster, key=lambda r: (int(r["team_id"]), r["name"])) if r["injured_until"])
    if not injured_rows:
        injured_rows = f'<tr><td colspan="5">No players are injured for Round {next_round}.</td></tr>'

    log = sorted(state["applied"] + state["voided"], key=lambda r: str(r.get("submitted_at", "")), reverse=True)
    log_rows = "".join(
        f'<tr><td class="mono">R{r["round"]}</td><td>{escape(team_name.get(r["team_id"], r["team_id"]))}</td>'
        f'<td>{escape(r.get("player_name", ""))}</td>'
        f'<td>{escape(health.CATALOG.get(r.get("treatment"), {}).get("label", str(r.get("treatment"))))}</td>'
        f'<td>{"Applied" if "void_reason" not in r else "Voided: " + escape(r["void_reason"])}</td></tr>'
        for r in log[:60])
    if not log_rows:
        log_rows = '<tr><td colspan="5">No treatments yet.</td></tr>'

    if open_now:
        status = (f'Requests are open for <b>Round {next_round}</b>. Each team may book up to '
                  f'{health.MAX_PER_ROUND} treatments for this round, one per player.')
    elif next_round < health.START_ROUND:
        status = (f'The Health Hub opens for <b>Round {health.START_ROUND}</b>. Requests can be submitted once '
                  f'Round {health.START_ROUND - 1} has been played.')
    else:
        status = 'The regular season is over; no further treatments can be booked.'

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Player Health Hub</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@600;700;800&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=IBM+Plex+Mono:wght@400;500;600&display=swap">
<style>
:root{{
  --paper:#eef2ea; --ink:#16201a; --muted:#5b6b5e; --line:#d6decd;
  --accent:#b8811f; --accent-ink:#3a2a08; --pitch:#2f5233; --pitch-ink:#eef2ea;
  --navy:#223a5e; --navy-ink:#eef2ea; --surface:#f7f9f4; --med:#1f6f78; --bad:#b4472f; --good:#2f7a4f;
  --shadow: 0 1px 2px rgba(22,32,26,.06), 0 4px 14px rgba(22,32,26,.05);
}}
@media (prefers-color-scheme: dark){{
  :root:not([data-theme="light"]){{
    --paper:#111611; --ink:#e7ece1; --muted:#93a091; --line:#2a352a;
    --accent:#d9a44a; --accent-ink:#1c1404; --pitch:#4c7a52; --pitch-ink:#0d130e;
    --navy:#4a6693; --navy-ink:#0d130e; --surface:#171d17; --med:#4fb3bd; --bad:#e07a5c; --good:#4fae76;
    --shadow: 0 1px 2px rgba(0,0,0,.3), 0 4px 18px rgba(0,0,0,.35);
  }}
}}
:root[data-theme="dark"]{{
    --paper:#111611; --ink:#e7ece1; --muted:#93a091; --line:#2a352a;
    --accent:#d9a44a; --accent-ink:#1c1404; --pitch:#4c7a52; --pitch-ink:#0d130e;
    --navy:#4a6693; --navy-ink:#0d130e; --surface:#171d17; --med:#4fb3bd; --bad:#e07a5c; --good:#4fae76;
    --shadow: 0 1px 2px rgba(0,0,0,.3), 0 4px 18px rgba(0,0,0,.35);
}}
*{{box-sizing:border-box;}}
body{{margin:0;background:var(--paper);color:var(--ink);font-family:"Source Serif 4",Georgia,serif;line-height:1.5;}}
.mono{{font-family:"IBM Plex Mono",ui-monospace,monospace;}}
h1,h2,h3{{font-family:"Big Shoulders Display",sans-serif;text-transform:uppercase;letter-spacing:.02em;margin:0;}}
.num{{font-variant-numeric:tabular-nums;text-align:right;}}
.masthead{{background:var(--med);color:#fff;padding:28px clamp(16px,4vw,48px);}}
.masthead-inner{{max-width:1180px;margin:0 auto;}}
.masthead h1{{font-size:clamp(26px,4vw,38px);font-weight:800;}}
.masthead p{{font-family:"IBM Plex Mono",monospace;font-size:12.5px;opacity:.9;margin:6px 0 0;}}
.wrap{{max-width:1180px;margin:0 auto;padding:28px clamp(16px,4vw,48px) 70px;}}
section{{margin-bottom:34px;}}
.section-head{{border-bottom:2px solid var(--ink);padding-bottom:6px;margin-bottom:14px;display:flex;justify-content:space-between;align-items:baseline;flex-wrap:wrap;gap:8px;}}
.section-head h2{{font-size:21px;}}
.note{{font-family:"IBM Plex Mono",monospace;font-size:12px;color:var(--muted);}}
.status{{background:var(--surface);border:1px solid var(--line);border-left:5px solid var(--med);border-radius:4px;padding:12px 16px;box-shadow:var(--shadow);margin-bottom:18px;}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px;}}
.card{{background:var(--surface);border:1px solid var(--line);border-radius:4px;box-shadow:var(--shadow);padding:16px 18px;}}
ul.rules{{margin:0;padding-left:20px;}} ul.rules li{{margin-bottom:6px;}}
table{{width:100%;border-collapse:collapse;font-size:13px;background:var(--surface);border:1px solid var(--line);box-shadow:var(--shadow);}}
thead th{{background:var(--navy);color:var(--navy-ink);text-align:left;padding:8px;font-family:"IBM Plex Mono",monospace;font-size:10px;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap;}}
thead th.num{{text-align:right;}}
tbody td{{padding:7px 8px;border-top:1px solid var(--line);}}
.table-scroll{{overflow-x:auto;}}
label{{display:block;font-family:"IBM Plex Mono",monospace;font-size:11px;letter-spacing:.04em;text-transform:uppercase;color:var(--muted);margin:10px 0 4px;}}
select,input{{width:100%;padding:9px 10px;font-size:15px;border:1px solid var(--line);border-radius:4px;background:var(--paper);color:var(--ink);font-family:inherit;}}
button{{margin-top:14px;background:var(--med);color:#fff;border:0;border-radius:4px;padding:11px 18px;font-size:15px;font-weight:600;cursor:pointer;}}
button:disabled{{opacity:.5;cursor:not-allowed;}}
.hh-msg{{margin-top:10px;font-size:14px;}} .hh-msg.ok{{color:var(--good);}} .hh-msg.err{{color:var(--bad);}}
.hh-player{{margin-top:10px;font-size:14px;color:var(--muted);}}
footer{{max-width:1180px;margin:0 auto;padding:0 clamp(16px,4vw,48px) 50px;color:var(--muted);font-size:12px;font-family:"IBM Plex Mono",monospace;}}
{NAV_CSS}
</style>
</head>
<body>
{render_nav("health")}
<header class="masthead"><div class="masthead-inner">
  <h1>Player Health Hub</h1>
  <p>{escape(config["league_name"])} &middot; pay for treatment to speed up injuries or lift a player's condition for the next round</p>
</div></header>
<div class="wrap">
  <div class="status">{status}</div>

  <section>
    <div class="section-head"><h2>Treatments</h2><span class="note">paid from cash on hand</span></div>
    <div class="table-scroll"><table>
      <thead><tr><th>Treatment</th><th>For</th><th>Effect</th><th class="num">Cost</th></tr></thead>
      <tbody>{cat_rows}</tbody>
    </table></div>
  </section>

  <section class="grid">
    <div class="card">
      <h3>Rules</h3>
      <ul class="rules">
        <li>The Health Hub opens for Round {health.START_ROUND}. A treatment always applies to the <b>next round to be played</b>.</li>
        <li>Up to <b>{health.MAX_PER_ROUND} treatments per team per round</b>, and only one treatment per player per round.</li>
        <li>Rehab is for injured players; Recovery and Sports-Science are for healthy players. Condition can't rise above Excellent.</li>
        <li>The cost is deducted from your team's cash on the Budget Dashboard. It does <b>not</b> reduce the Revenue component of your Season Scorecard.</li>
        <li>Requests are processed about every 30 minutes. Check the Dashboard's Player Condition report before you submit your lineup to confirm the treatment took effect.</li>
        <li>A request that fails a check (not enough cash, round already played, limit reached) is voided and listed in the log below with the reason. Voided requests cost nothing.</li>
        <li>A treatment is a business decision: explain it in that round's lineup rationale, where it is scored under Business/Financial Reasoning.</li>
      </ul>
    </div>
    <div class="card">
      <h3>Book a Treatment</h3>
      <p class="sub-backend-warning" hidden>Backend not configured &mdash; requests are disabled.</p>
      <label for="hh-team">Team</label><select id="hh-team"></select>
      <label for="hh-pin">Team PIN</label><input id="hh-pin" type="password" inputmode="numeric" autocomplete="off">
      <label for="hh-player">Player</label><select id="hh-player"></select>
      <div class="hh-player" id="hh-player-info"></div>
      <label for="hh-treat">Treatment</label><select id="hh-treat"></select>
      <div class="hh-player" id="hh-cash"></div>
      <button id="hh-submit" type="button">Book treatment for Round {next_round}</button>
      <div class="hh-msg" id="hh-msg"></div>
    </div>
  </section>

  <section>
    <div class="section-head"><h2>Team Medical Budget</h2><span class="note">Round {next_round} &middot; cash net of all spending</span></div>
    <div class="table-scroll"><table>
      <thead><tr><th>Team</th><th class="num">Cash Available</th><th class="num">Medical Spend (season)</th><th class="num">Treatments Used, Round {next_round}</th></tr></thead>
      <tbody>{team_rows}</tbody>
    </table></div>
  </section>

  <section>
    <div class="section-head"><h2>Injury Report</h2><span class="note">players injured for Round {next_round}</span></div>
    <div class="table-scroll"><table>
      <thead><tr><th>Team</th><th>Player</th><th>Pos</th><th class="num">OVR</th><th class="num">Out Through</th></tr></thead>
      <tbody>{injured_rows}</tbody>
    </table></div>
  </section>

  <section>
    <div class="section-head"><h2>Treatment Log</h2><span class="note">most recent first</span></div>
    <div class="table-scroll"><table>
      <thead><tr><th>Round</th><th>Team</th><th>Player</th><th>Treatment</th><th>Status</th></tr></thead>
      <tbody>{log_rows}</tbody>
    </table></div>
  </section>
</div>
<footer>{escape(config["league_name"])} &middot; Player Health Hub &mdash; rules in engine/health.py; updates after every processed request and resolved round</footer>
<script>const HH_DATA = {json.dumps(data)};</script>
<script src="../assets/config.js"></script>
<script src="../assets/health.js"></script>
</body>
</html>'''


if __name__ == "__main__":
    config = load_json("league_config.json")
    html = render(config, render_dashboard.load_players(), load_json("team_finances.json"),
                  load_json("player_injuries.json", {}), health.load())
    out_dir = os.path.join(BASE, "health-site")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w") as f:
        f.write(html)
    print(f"Rendered -> {os.path.join(out_dir, 'index.html')}")
